FROM openjdk:8-jre-alpine
USER root

COPY ./target/scala-2.13/classes/controllers/ ./tmp

WORKDIR /tmp

ENTRYPOINT ["java","MainClass"]

#ENV SCALA_HOME=/usr/share/scala


#
#ENV JAVA_HOME=/usr/lib/jvm/java-1.8-openjdk
#ENV PATH="$JAVA_HOME/bin:${PATH}"
#


##install scala
#RUN apk add --no-cache --virtual=.build-dependencies wget ca-certificates && \
#  apk add --no-cache bash && \
#  cd "/tmp" && \
#  wget "https://github.com/lampepfl/dotty/releases/download/2.13.10/scala2-2.13.10.tar.gz" && \
#  tar xzf "scala2-2.13.10.tar.gz" && \
#  mkdir "${SCALA_HOME}" && \
#  rm "/tmp/scala2-2.13.10/bin/"*.bat && \
#  mv "/tmp/scala2-2.13.10/bin" "/tmp/scala2-2.13.10/lib" "${SCALA_HOME}" && \
#  ln -s "${SCALA_HOME}/bin/"* "/usr/bin/" && \
#  apk del .build-dependencies && \
#  rm -rf "/tmp/"*
#
#
#RUN \
#  apk add --no-cache --virtual=.build-dependencies bash curl bc ca-certificates && \
#  cd "/tmp" && \
#  update-ca-certificates && \
#  scala -version && \
#  scalac -version && \
#  curl -fsL https://github.com/sbt/sbt/releases/downloaRUN \
#  apk add --no-cache --virtual=.build-dependencies bash curl bc ca-certificates && \
#  cd "/tmp" && \
#  update-ca-certificates && \
#  scala -version && \
#  scalac -version && \
#  curl -fsL https://github.com/sbt/sbt/releases/download/v1.7.2/sbt-1.7.2.tgz | tar xfz - -C /usr/local && \
#  $(mv /usr/local/sbt-launcher-packaging-1.7.2 /usr/local/sbt || true) && \
#  ln -s /usr/local/sbt/bin/* /usr/local/bin/ && \
#  apk del .build-dependencies && \
#  rm -rf "/tmp/"*d/v1.7.2/sbt-1.7.2.tgz | tar xfz - -C /usr/local && \
#  $(mv /usr/local/sbt-launcher-packaging-1.7.2 /usr/local/sbt || true) && \
#  ln -s /usr/local/sbt/bin/* /usr/local/bin/ && \
#  apk del .build-dependencies && \
#  rm -rf "/tmp/"*



#EXPOSE 9004
#RUN sbt compile -Dsbt.rootdir=true

#CMD [ "sbt","-Dsbt.rootdir=true", "run" ]
